CREDENTIALS_FILE = "credentials.json"           # YOUR GOOGLE SHEETS CREDENTIALS FILE
SHEET_NAME = "Spese"               # YOUR GOOGLE SHEETS NAME
WORKSHEET= "January"                            # SHEETS WORKSHEET NAME WHERE YOU WANT TO WRITE THE DATA

# PAYPAL
PAYPAL_INPUT_FILE = "paypalinput.csv"           # NAME OF THE PAYPAL INPUT FILE IN THE INPUT FOLDER

# N26
N26_INPUT_FILE = "n26input.csv"                 # NAME OF THE N26 INPUT FILE IN THE INPUT FOLDER

# INTESA
INTESASP_INPUT_FILE = "intesaInput.csv"                 # NAME OF THE INTESA SP INPUT FILE IN THE INPUT FOLDER

# DO NOT CHANGE THE FOLLOWING LINES UNLESS YOU KNOW WHAT YOU ARE DOING
PAYPAL_BLACKLIST_FILE = "paypal_blacklist"  # BLACKLIST FILE FOR PAYPAL IN THE CONFIG FOLDER
PAYPAL_CATEGORY_FILE = "paypal_category"    # CATEGORY FILE FOR PAYPAL IN THE CONFIG FOLDER
N26_BLACKLIST_FILE = "n26_blacklist"        # BLACKLIST FILE FOR N26 IN THE CONFIG FOLDER
N26_CATEGORY_FILE = "n26_category"          # CATEGORY FILE FOR N26 IN THE CONFIG FOLDER
INTESASP_BLACKLIST_FILE = "intesa_blacklist" # BLACKLIST FILE FOR INTESA IN THE CONFIG FOLDER
INTESASP_CATEGORY_FILE = "intesa_category"  # CATEGORY FILE FOR INTESA IN THE CONFIG FOLDER